### PR TITLE
Replace some make targets with tools.mk

### PR DESCRIPTION
**Pull request by kuenishi**
Unify the way we use dialyzer and other make targets. Or maybe even we move out to rebar3?

### CODE REVIEW

**Comment by kuenishi** [comment]
Should be rebased after #23 merged.

**Comment by slfritchie** [comment]
#23 has been merged

**Comment by kuenishi** [comment]
Rebased and force-pushed :smiling_imp:

**Comment by slfritchie** [comment]
+1, thanks!

**Pull request merged**
