### PR TITLE
FLU1 Factorization 1/N: Introduce ranch and factor out socket handling process

### PR DESCRIPTION
**Pull request by shino**
This PR introduces Ranch as network transport abstraction and adds socket handling
processes ("protocol handler" in Ranch's terminology), as the first round of FLU1 factorization.

TODO for later effort: Remove machi_listener_sup _if possible_

Not directly related commits are included in this PR:
- 3bc5ec4 : set longer timeout for huge write test of `machi_file_proxy_test`
- c3e961b , 1e42a7f, 77a1ffd : cosmetics and refactoring for initialization phase of test modules

### CODE REVIEW

**Comment by jadeallenx** [comment]
@shino This looks great so far! Nice work!

**Comment by shino** [comment]
Ready for review, I hope :hammer:

**Comment by jadeallenx** [comment]
Planning to look at this tomorrow.

**Comment by slfritchie** [comment]
Preliminary +1 from me, yay.

**Comment by shino** [comment]
Rebased on current master and force-pushed.

**Comment by jadeallenx** [comment]
The only confirmed test failure was the known doublewrite problem. 

I **did** see this message scroll by but I'm not sure if its important:

``` shel
machi_flu1_test: flu_projection_smoke_test...
=ERROR REPORT==== 8-Dec-2015::16:18:06 ===
Ranch listener smoke_flu_listener had connection process started with machi_flu1_net_server:start_link/4 at <0.4450.0> exit with reason: badarg
[0.117 s] ok
```

I'm a little concerned the try/after block might be masking a test failure we should care about.

Otherwise, this is **suuuuuper** cool. :cake:

**Comment by shino** [comment]
Rebased and force pushed again.

**Comment by shino** [comment]
> Ranch listener smoke_flu_listener had connection process started with machi_flu1_net_server:start_link/4 at <0.4450.0> exit with reason: badarg

I saw the line once in a while in `machi_flu1_test`... but not sure why.

**Comment by shino** [comment]
> Ranch listener smoke_flu_listener had connection process started with
> machi_flu1_net_server:start_link/4 at <0.4450.0> exit with reason: badarg

Identified. Race between `machi_flu1` and `machi_flu1_net_server` at cleanup phase,
if `machi_flu1` dies first, ets table has gone and net server process gets `badarg`.
I just added a comment at eef00e4.

**Comment by slfritchie** [comment]
Hmm, yes, if that table disappears because the FLU proc has exited (clean shutdown or crash), the 'badarg' is good behavior in that it causes the net server proc to crash and so is "safe" from a Machi operation perspective.  That probably also closes the TCP connection without a reply, which isn't very polite, but better than sending nonsense?

**Comment by jadeallenx** [comment]
:+1: 

@shino great work! Thank you for digging in on that race condition.

**Comment by shino** [comment]
Thanks for review & valuable comments! > Scott & Mark

**Pull request merged**
